version: "3.8"
services:
  api:
    build: .
    restart: "always"
    environment:
      FLASK_APP: run.py
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - /application/static/:/static
    depends_on:
      - api
    ports:
      - 80:80