version: "3.8"
services:
  api:
    build: .
    restart: "always"
    environment:
      FLASK_APP: run.py
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    command: ["python", "run.py"]